=== cemartins/juffrou/juffrou-xml/src/test/resources/juffrou-xml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2013 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="xml">
		<xs:complexType>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Country"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="serializer">
		<xs:complexType>
			<xs:attribute name="ref">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="simpledate"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="id">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="simpledate"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="class">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
						<xs:enumeration value="net.sf.juffrou.xml.test.dom.SimpleDateSerializer"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="root-element">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:sequence minOccurs="0">
					<xs:element ref="xml"/>
					<xs:element ref="serializer"/>
				</xs:sequence>
				<xs:element ref="element" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="xml">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Person"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="net.sf.juffrou.xml.test.dom.Address"/>
						<xs:enumeration value="net.sf.juffrou.xml.test.dom.Country"/>
						<xs:enumeration value="net.sf.juffrou.xml.test.dom.Person"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="preferences">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="collectionWithSizeAttribute"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="mapping">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="preferences"/>
				<xs:element ref="serializer"/>
				<xs:element ref="root-element" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="element">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="serializer" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="xml">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="founded"/>
						<xs:enumeration value="homeTown"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="java.util.Date"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="property" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="birthDay"/>
						<xs:enumeration value="firstName"/>
						<xs:enumeration value="founded"/>
						<xs:enumeration value="home.city"/>
						<xs:enumeration value="lastName"/>
						<xs:enumeration value="name"/>
						<xs:enumeration value="partyLeaders"/>
						<xs:enumeration value="people"/>
						<xs:enumeration value="president"/>
						<xs:enumeration value="provinces"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="collectionWithSizeAttribute" type="xs:boolean"/>
</xs:schema>

=== cemartins/juffrou/juffrou-xml/src/test/resources/attributes-xml-mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		 xmlns="http://juffrou.sourceforge.net/juffrou-xml"
         xsi:schemaLocation="http://juffrou.sourceforge.net/juffrou-xml http://juffrou.sourceforge.net/juffrou-xml/schemas/juffrou-xml.xsd">

	<preferences>
		<collectionWithSizeAttribute>false</collectionWithSizeAttribute>
	</preferences>

	<serializer id="simpledate" class="net.sf.juffrou.xml.test.dom.SimpleDateSerializer"/>

	<root-element xml="Person" type="net.sf.juffrou.xml.test.dom.Person">
		<element property="firstName">
			<xml id="firstName" node="attribute" />
		</element>
		<element property="lastName" />
		<element property="birthDay">
			<serializer ref="simpledate" />
		</element>
	</root-element>
	
</mapping>
